### ISSUE TITLE
API: Add endpoint to get one NetworkParameter

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/vega#5723]
Add endpoints in gRPC, GraphQL and REST that enable fetching **one** `NetworkParameter`.

## gRPC

```proto
service TradingDataService {
  rpc NetworkParameterByID(NetworkParameterByIDRequest) returns (NetworkParameterByIDResponse);
}

message NetworkParameterByIDRequest {
  string key = 1;
}

message NetworkParameterByIDResponse {
  vega.NetworkParameter parameter = 1;
}
```

## GraphQL
```graphql
type Query {
  networkParameter(
    id: ID!
  ): NetworkParameterValue!
}
```

## REST
```yaml
# grpc-rest-bindings.yml
- selector: api.v1.TradingDataService.NetworkParameterByID
  get: '/network/parameters/{key}'
```
