### ISSUE TITLE
[wallet][0.55] if n06 is down at wallet service startup, the wallet does not try other nodes

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5963]
With this config:

```toml
Name = "fairground"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = ["api.n06.testnet.vega.xyz:3007", "api.n07.testnet.vega.xyz:3007", "api.n08.testnet.vega.xyz:3007", "api.n09.testnet.vega.xyz:3007", "api.n10.testnet.vega.xyz:3007", "api.n11.testnet.vega.xyz:3007", "api.n12.testnet.vega.xyz:3007"]
    Retries = 5
  [API.REST]
    Hosts = ["https://api.n06.testnet.vega.xyz", "https://api.n07.testnet.vega.xyz", "https://api.n08.testnet.vega.xyz", "https://api.n09.testnet.vega.xyz", "https://api.n10.testnet.vega.xyz", "https://api.n11.testnet.vega.xyz", "https://api.n12.testnet.vega.xyz"]
  [API.GraphQL]
    Hosts = ["https://api.n06.testnet.vega.xyz/graphql", "https://api.n07.testnet.vega.xyz/graphql", "https://api.n08.testnet.vega.xyz/graphql", "https://api.n09.testnet.vega.xyz/graphql", "https://api.n10.testnet.vega.xyz/graphql", "https://api.n11.testnet.vega.xyz/graphql", "https://api.n12.testnet.vega.xyz/graphql"]

[TokenDApp]
  URL = "token.fairground.wtf"
  LocalPort = 1848

[Console]
  URL = "console.fairground.wtf"
  LocalPort = 1847
```

and this command:

```bash
./vegawallet service run --network fairground
```

The wallet service will fail to start up if n06 is down:
```bash
./vegawallet service run --network fairground

✗ You are running an unreleased version of the Vega wallet (v0.55.0+dev).
  Use it at your own risk!

✗ couldn't get network statistics: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:3002: connect: connection refused"
```

Removing n06 from the GRPC hosts leads to success

# Tasks
- [ ] Make startup version check iterate through nodes until one succeeds
- [ ] Extend existing functionality to remove hosts that don't act correctly to drop nodes that respond incorrectly at startup
