### ISSUE TITLE
Typo in the vegavisor config

### ISSUE THREAD

**Issue by daniel1302** [vegaprotocol/vega#7927]
# Problem encountered|

There is a typo spotted by Ed on discord.

We have the following config in vegavisor run-config:

```toml
[autoInstall]
  enabled = true
  repositoryOwner = "vegaprotocol"
  repository = "vega"
  [autoInstall.assets]
    [autoInstall.assets.vega]
      assset_name = "vega-linux-amd64.zip"
      binary_name = "vega"
    # We use vega datanode subcommand to start data-node. See example below
    [autoInstall.assets.data_node]
      assset_name = "vega-linux-amd64.zip"
      binary_name = "vega"
```

There is a typo in word `assset_name` it has `3 s'` chars instead of 2.

- `assset_name` - this is now
- `asset_name` - this should be 

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature
